name: DVC pull data

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    run-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: python my_script.py
