name: DVC pull data

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install dvc
    - run: pip install -U "dvc[gdrive]"
    - run: dvc remote modify myremote gdrive_client_id ${{ secrets.DVC_ID }}
    - run: dvc remote modify myremote gdrive_client_secret ${{ secrets.DVC_SECRET }}
    - run: dvc pull


